Repository PharmQuest/FE, pull requests merged in 2025-02, with the labels that each got.

#79 [feat/#77] 로그인 화면 UI 구현완료
  public/images/google-login.webp
  public/images/index.ts
  public/images/kakao-login.webp
  public/images/login-bg.webp
  public/images/naver-login.webp
  public/svgs/google.svg
  public/svgs/index.ts
  public/svgs/kakao.svg
  public/svgs/logo-symbol.svg
  public/svgs/logo-text.svg
  public/svgs/naver.svg
  src/components/layout/Footer.tsx
  src/components/layout/Header.tsx
  src/pages/login/index.tsx
Labels: 🎨 Design

#80 [feat/#76] 약국찾기 반응형 구현완료
  public/images/index.ts
  public/images/pharamacy-deatil-default.webp
  public/images/pharamacy-default.webp
  public/svgs/index.ts
  public/svgs/list-view.svg
  public/svgs/map-view.svg
  src/pages/map/components/MapComponent.tsx
  src/pages/map/components/MapSearchHeader.tsx
  src/pages/map/components/PharmacyDetailPanel.tsx
  src/pages/map/components/PharmacyItem.tsx
  src/pages/map/components/SearchPanel.tsx
  src/pages/map/index.tsx
  tailwind.config.ts
Labels: ✨ Feature, 🎨 Design

#78 [feat/#20] 헤더 수정
  public/images/ad-mobile.webp
  public/images/ad-web.webp
  public/images/index.ts
  src/components/common/Search.tsx
  src/components/layout/Footer.tsx
  src/components/layout/Header.tsx
  src/pages/index.tsx
Labels: ✨ Feature, 🎨 Design

#86 [feat/#83] 약국 상세정보 탭 UI/UX 개선완료
  public/svgs/arrive.svg
  public/svgs/call.svg
  public/svgs/close.svg
  public/svgs/depart.svg
  public/svgs/index.ts
  public/svgs/time.svg
  src/pages/map/components/PharmacyDetailPanel.tsx
  src/pages/map/components/PharmacyItem.tsx
  src/pages/map/components/PharmacyList.tsx
  src/pages/map/components/RatingStars.tsx
  src/pages/map/components/detailPanel/ActionButtons.tsx
  src/pages/map/components/detailPanel/Info.tsx
  src/pages/map/components/detailPanel/Overview.tsx
  src/pages/map/components/detailPanel/PanelContent.tsx
  src/pages/map/components/detailPanel/PharmacyDetailPanel.tsx
  src/pages/map/components/detailPanel/PharmacyHeader.tsx
  src/pages/map/components/detailPanel/RatingStars.tsx
  src/pages/map/components/detailPanel/Reviews.tsx
  src/pages/map/components/detailPanel/TabNavigation.tsx
  src/pages/map/index.tsx
Labels: ✨ Feature, 🎨 Design

#88 [feat/#87] 로그인 페이지 반응형 구현완료
  public/images/index.ts
  public/images/m-google-login.webp
  public/images/m-kakao-login.webp
  public/images/m-naver-login.webp
  public/svgs/logo-symbol.svg
  src/pages/login/index.tsx
Labels: 🎨 Design

#92 [feat/#20] 메인 반응형 수정
  src/components/common/Search.tsx
  src/components/layout/Header.tsx
  src/pages/index.tsx
Labels: 🎨 Design

#90 [feat/#85] 커뮤니티 페이지 반응형 구현
  public/svgs/account_circle.svg
  public/svgs/arrow-right.svg
  public/svgs/camera.svg
  public/svgs/comment.svg
  public/svgs/create-post.svg
  public/svgs/index.ts
  public/svgs/kebab.svg
  public/svgs/like.svg
  public/svgs/notice.svg
  public/svgs/plus.svg
  public/svgs/post.svg
  public/svgs/scrap.svg
  src/components/layout/Header.tsx
  src/hooks/community/useUserCount.ts
  src/pages/community/bestposts/index.tsx
  src/pages/community/components/Dropdown.tsx
  src/pages/community/components/MobilePostItem.tsx
  src/pages/community/components/PageNavigator.tsx
  src/pages/community/components/PopularPostItem.tsx
  src/pages/community/components/PopularPostList.tsx
  src/pages/community/components/PostList.tsx
  src/pages/community/components/SubjectTag.tsx
  src/pages/community/components/UserNavbar.tsx
  src/pages/community/create/index.tsx
  src/pages/community/index.tsx
  src/pages/community/modify/[postId]/index.tsx
  src/pages/community/post/[postId]/index.tsx
  src/pages/community/post/components/CommentInput.tsx
  src/pages/community/post/components/CommentItem.tsx
  src/pages/community/post/components/CommentList.tsx
  src/pages/community/post/components/ReplyItem.tsx
  src/pages/community/post/components/ViewPost.tsx
  src/pages/community/posts/index.tsx
  src/pages/map/components/detailPanel/ActionButtons.tsx
  src/pages/mypage/index.tsx
Labels: ✨ Feature, 🎨 Design

#91 [feat/#89] 나의활동 댓글 및 알림 반응형 구현
  src/pages/community/activities/components/ActivitiesNav.tsx
  src/pages/community/activities/components/MyCommentItem.tsx
  src/pages/community/activities/components/MyCommentList.tsx
  src/pages/community/activities/components/MyNotificationItem.tsx
  src/pages/community/activities/components/MyNotificationList.tsx
  src/pages/community/activities/index.tsx
  src/pages/community/components/TextButton.tsx
  src/pages/community/post/components/CommentInput.tsx
Labels: 🎨 Design

#95 [refactor/#94] 약국찾기 디자인 수정완료
  public/svgs/close.svg
  public/svgs/map-pin.svg
  src/pages/map/components/IsOpenTag.tsx
  src/pages/map/components/PharmacyItem.tsx
  src/pages/map/components/PharmacyList.tsx
  src/pages/map/components/SearchPanel.tsx
  src/pages/map/components/detailPanel/ActionButtons.tsx
  src/pages/map/components/detailPanel/Overview.tsx
  src/pages/map/components/detailPanel/PharmacyDetailPanel.tsx
  src/pages/map/components/detailPanel/PharmacyHeader.tsx
  src/pages/map/components/detailPanel/TabNavigation.tsx
  src/pages/map/index.tsx
Labels: 🎨 Design, 🔨 Refactor

#98 [feat/#82] 공용 컴포넌트 추가/수정 및 반응형 추가
  src/components/layout/Header.tsx
  src/pages/community/components/NoticeModal.tsx
  src/pages/community/post/components/ReportModal.tsx
  src/pages/index.tsx
Labels: ✨ Feature, 🎨 Design

#102 [feat/#100] 게시글 이미지 등록 추가
  next.config.ts
  src/apis/axios-instance.ts
  src/hooks/community/usePostMutation.ts
  src/hooks/community/useUserCount.ts
  src/pages/community/create/index.tsx
  src/pages/community/modify/[postId]/index.tsx
  src/pages/community/post/[postId]/index.tsx
  src/pages/community/post/components/CommentInput.tsx
  src/pages/community/post/components/PostMenu.tsx
  src/pages/community/post/components/ReportModal.tsx
  src/pages/community/post/components/ViewPost.tsx
Labels: ✨ Feature, 📬 API

#104 [feat/#103] 로그인 전역상태 처리 및 UserNavbar 로그인 상태 연동
  src/pages/_app.tsx
  src/pages/community/components/NoticeModal.tsx
  src/pages/community/components/UserNavbar.tsx
  src/pages/community/create/index.tsx
  src/pages/community/modify/[postId]/index.tsx
  src/pages/community/post/[postId]/index.tsx
  src/pages/community/post/components/PostMenu.tsx
  src/pages/community/post/components/ReportModal.tsx
  src/store/useAuthStore.ts
  src/store/useModalStore.ts
Labels: ✨ Feature, 🎨 Design

#113 [feat/#111] 메인 수정
  public/svgs/index.ts
  public/svgs/map-pin-thin.svg
  public/svgs/search-thin.svg
  public/svgs/x-thin.svg
  src/components/common/FilterButton.tsx
  src/components/common/MedicineCard.tsx
  src/components/common/Search.tsx
  src/components/common/SupplementCard.tsx
  src/components/layout/AdditionalHeader.tsx
  src/components/layout/Header.tsx
  src/hooks/community/useUserCount.ts
  src/pages/community/components/SkeletonItem.tsx
  src/pages/community/components/UserNavbar.tsx
  src/pages/community/post/[postId]/index.tsx
  src/pages/community/post/components/CommentInput.tsx
  src/pages/community/post/components/CommentItem.tsx
  src/pages/community/post/components/CommentMenu.tsx
  src/pages/community/post/components/ReplyItem.tsx
  src/pages/index.tsx
Labels: 🎨 Design

#120 [feat/#99] 해외인기영양제 api 연결
  next.config.ts
  src/components/common/SupplementCard.tsx
  src/pages/supplements/[supplementId]/index.tsx
  src/pages/supplements/components/MoreSupplements.tsx
  src/pages/supplements/components/ProductBasicInfo.tsx
  src/pages/supplements/index.tsx
Labels: ✨ Feature, 🎨 Design, 📬 API

#121 [feat/#114] 커뮤니티 회원 정보 연동
  public/svgs/x.svg
  src/components/common/Search.tsx
  src/components/layout/Header.tsx
  src/hooks/community/useScroll.ts
  src/pages/community/components/UserNavbar.tsx
  src/pages/community/create/index.tsx
  src/pages/community/post/[postId]/index.tsx
  src/pages/community/post/components/CommentInput.tsx
  src/pages/community/post/components/CommentItem.tsx
  src/pages/community/post/components/CommentList.tsx
  src/pages/community/post/components/ReplyItem.tsx
  src/pages/community/post/components/ReportModal.tsx
  src/pages/community/post/components/ViewPost.tsx
  src/pages/community/posts/index.tsx
  src/pages/mypage/index.tsx
Labels: ✨ Feature, 📬 API

#122 [feat/#107] 커뮤니티 회원 상태 관리
  src/apis/axios-instance.ts
  src/pages/community/components/CommunityModal.tsx
  src/pages/community/create/index.tsx
  src/pages/community/modify/[postId]/index.tsx
  src/pages/community/post/[postId]/index.tsx
  src/pages/community/post/components/CommentInput.tsx
  src/pages/community/post/components/CommentItem.tsx
  src/pages/community/post/components/CommentList.tsx
  src/pages/community/post/components/DeletedComment.tsx
  src/pages/community/post/components/PostMenu.tsx
  src/store/useAuthStore.ts
  src/utils/cookie.ts
Labels: ✨ Feature, 📬 API, 🔨 Refactor

#126 [feat/#125] 인기 게시글 API 연동
  public/favicon.svg
  src/apis/axios-instance.ts
  src/hooks/community/useCommentMutation.ts
  src/hooks/community/usePostMutation.ts
  src/pages/_app.tsx
  src/pages/community/bestposts/index.tsx
  src/pages/community/components/PageNavigator.tsx
  src/pages/community/components/PopularPostItem.tsx
  src/pages/community/components/PopularPostList.tsx
  src/pages/community/components/PostList.tsx
  src/pages/community/components/UserNavbar.tsx
  src/pages/community/index.tsx
  src/pages/community/post/components/CommentInput.tsx
  src/pages/community/post/components/CommentItem.tsx
  src/pages/community/post/components/CommentList.tsx
  src/pages/community/post/components/CommentMenu.tsx
  src/pages/community/post/components/DeletedComment.tsx
  src/pages/community/post/components/ReplyItem.tsx
Labels: ✨ Feature, 📬 API, 🔨 Refactor

#129 [feat/#108] 약국 스크랩 연동 완료
  src/hooks/map/usePharmacyScrap.ts
  src/pages/map/components/detailPanel/ActionButtons.tsx
  src/pages/map/components/detailPanel/PharmacyDetailPanel.tsx
Labels: ✨ Feature, 📬 API

#123 [feat/#117] 메인화면 필터버튼 영양제API 연결
  src/components/common/FilterButtonList.tsx
  src/pages/index.tsx
  src/pages/mypage/supplement/index.tsx
Labels: ✨ Feature, 📬 API

#127 [feat/#112] 상비약 리스트 및 단일 조회 API 연동
  next.config.ts
  src/components/common/MedicineCard.tsx
  src/components/common/MedicineCardList.tsx
  src/hooks/medicine/useFormatMedicineCategory.ts
  src/hooks/medicine/useMedicineList.ts
  src/pages/medicines/[medicineId]/index.tsx
  src/pages/medicines/components/InfoRow.tsx
  src/pages/medicines/components/MedicineDetail.tsx
  src/pages/medicines/components/Section.tsx
  src/pages/medicines/index.tsx
  src/types/medicine.ts
Labels: ✨ Feature, 📬 API, 🔨 Refactor

#135 [feat#132] 나의 활동 페이지 API 연동
  public/svgs/checkbox.svg
  public/svgs/checkbox_on.svg
  public/svgs/index.ts
  src/apis/axios-instance.ts
  src/components/layout/AdditionalHeader.tsx
  src/components/layout/Header.tsx
  src/hooks/community/useFormatCategory.ts
  src/hooks/community/useUserCount.ts
  src/pages/_app.tsx
  src/pages/community/activities/components/ActivitiesNav.tsx
  src/pages/community/activities/components/MyCommentItem.tsx
  src/pages/community/activities/components/MyCommentList.tsx
  src/pages/community/activities/components/MyNotificationItem.tsx
  src/pages/community/activities/components/MyNotificationList.tsx
  src/pages/community/activities/index.tsx
  src/pages/community/components/MobilePostItem.tsx
  src/pages/community/components/PageNavigator.tsx
  src/pages/community/components/PostList.tsx
  src/pages/community/modify/[postId]/index.tsx
  src/pages/community/post/[postId]/index.tsx
  src/pages/community/post/components/ViewPost.tsx
  src/pages/community/posts/search/index.tsx
  src/pages/index.tsx
  src/pages/medicines/components/InfoRow.tsx
  src/pages/medicines/components/MedicineDetail.tsx
  src/pages/mypage/index.tsx
  src/pages/mypage/medicines/index.tsx
  src/pages/mypage/supplement/index.tsx
  src/pages/supplements/components/ProductBasicInfo.tsx
  src/store/useAuthStore.ts
Labels: ✨ Feature, 📬 API

#140 [feat/#139] 약국찾기 검색기능 구현
  package.json
  pnpm-lock.yaml
  src/pages/map/components/MapComponent.tsx
  src/pages/map/components/MapSearchHeader.tsx
  src/pages/map/components/SearchPanel.tsx
  src/pages/map/index.tsx
Labels: ✨ Feature

#144 [feat/#143] 약국 상세정보 구현
  src/pages/map/components/IsOpenTag.tsx
  src/pages/map/components/MapComponent.tsx
  src/pages/map/components/PharmacyItem.tsx
  src/pages/map/components/PharmacyList.tsx
  src/pages/map/components/detailPanel/Info.tsx
  src/pages/map/components/detailPanel/PanelContent.tsx
  src/pages/map/components/detailPanel/PharmacyHeader.tsx
Labels: ✨ Feature

#138 [feat/#134] 마이페이지 API 구현
  next.config.ts
  src/components/common/Search.tsx
  src/components/common/SupplementCard.tsx
  src/pages/mypage/components/PharmacysCard.tsx
  src/pages/mypage/index.tsx
  src/pages/mypage/pharmacys/index.tsx
  src/pages/mypage/supplement/index.tsx
  src/pages/supplements/[supplementId]/index.tsx
  src/pages/supplements/index.tsx
Labels: ✨ Feature, 📬 API

#145 [feat/#136] 홈 화면 게시글 API 연동
  src/components/common/SearchModal.tsx
  src/components/home/HomePostItem.tsx
  src/constants/FilterList.ts
  src/pages/index.tsx
  src/utils/.gitkeep
Labels: ✨ Feature, 📬 API

#149 [feat/#148] 유저 정보 조회 email 추가
  src/components/map/CurrentLocationButton.tsx
  src/pages/map/components/MapComponent.tsx
  src/pages/map/components/detailPanel/Info.tsx
  src/pages/mypage/components/PharmacysCard.tsx
  src/pages/mypage/index.tsx
  src/pages/mypage/pharmacys/index.tsx
  src/pages/supplements/components/MoreSupplements.tsx
  src/store/useAuthStore.ts
Labels: ✨ Feature

#147 [feat/#146] 커뮤니티 페이지 UI/UX 개선
  package.json
  pnpm-lock.yaml
  public/images/og-image.webp
  src/components/common/FilterButtonList.tsx
  src/components/layout/AdditionalHeader.tsx
  src/pages/community/bestposts/index.tsx
  src/pages/community/components/MobileSkeletonItem.tsx
  src/pages/community/components/MobileSkeletonList.tsx
  src/pages/community/components/PopularPostList.tsx
  src/pages/community/components/PopularSkeletonItem.tsx
  src/pages/community/components/PopularSkeletonList.tsx
  src/pages/community/components/PostList.tsx
  src/pages/community/components/Tag.tsx
  src/pages/community/index.tsx
  src/pages/community/post/[postId]/index.tsx
  src/pages/community/post/components/ViewPost.tsx
  src/pages/community/posts/index.tsx
Labels: ✨ Feature, 🎨 Design, 🔨 Refactor

#153 [refactor/#152] 커뮤니티 페이지 리팩토링
  src/components/common/Search.tsx
  src/components/common/SearchModal.tsx
Labels: 🔨 Refactor

#155 [feat/#154] 상비약 페이지 디자인 수정
  src/components/common/MedicineCard.tsx
  src/pages/community/components/PageNavigator.tsx
  src/pages/medicines/index.tsx
Labels: 🎨 Design

#151 [feat/#150] 마이페이지 및 해외인기영양제 수정
  src/components/common/SearchModal.tsx
  src/components/common/SupplementCard.tsx
  src/pages/mypage/index.tsx
  src/pages/supplements/[supplementId]/index.tsx
  src/pages/supplements/index.tsx
Labels: ✨ Feature, 🎨 Design, 📬 API

#166 [feat/#165] 해외인기영양제 페이지 광고 수정
  src/components/common/SupplementCard.tsx
Labels: ✨ Feature, 🎨 Design

#163 [style/#157] 커뮤니티 UI/UX 개선
  src/components/layout/AdditionalHeader.tsx
  src/components/layout/Header.tsx
  src/pages/community/bestposts/index.tsx
  src/pages/community/components/PopularPostItem.tsx
  src/pages/community/components/PopularPostList.tsx
  src/pages/community/components/PostList.tsx
  src/pages/community/index.tsx
  src/pages/community/post/[postId]/index.tsx
  src/pages/index.tsx
  src/pages/mypage/index.tsx
  src/pages/supplements/index.tsx
Labels: ✨ Feature, 🎨 Design

#170 [feat/#169] 신고한 게시글 임의 접근 방지
  src/pages/community/post/[postId]/index.tsx
Labels: ✨ Feature

#168 [refactor/#167] 공용 컴포넌트 사용성 증가
  src/components/common/PageNavigator.tsx
  src/pages/community/activities/components/MyCommentList.tsx
  src/pages/community/activities/components/MyNotificationList.tsx
  src/pages/community/bestposts/index.tsx
  src/pages/community/components/PostList.tsx
  src/pages/community/post/components/CommentList.tsx
  src/pages/medicines/index.tsx
  src/pages/mypage/index.tsx
  src/pages/mypage/medicines/index.tsx
  src/pages/mypage/pharmacys/index.tsx
  src/pages/mypage/supplement/index.tsx
  src/pages/supplements/index.tsx
Labels: 🔨 Refactor

#171 [feat/#162] 상비약 저장기능 구현
  src/components/common/Loader.tsx
  src/components/common/MedicineCard.tsx
  src/components/common/MedicineCardList.tsx
  src/hooks/medicine/useMedicineScrap.ts
  src/pages/medicines/components/MedicineDetail.tsx
  src/pages/medicines/index.tsx
  src/types/medicine.ts
Labels: ✨ Feature, 📬 API

#173 [feat/#172] UI/UX 개선
  src/components/common/Breadcrumb.tsx
  src/components/common/Button.tsx
  src/components/common/CategoryItem.tsx
  src/components/common/SearchModal.tsx
  src/pages/community/create/index.tsx
  src/pages/community/post/components/CommentInput.tsx
Labels: 🎨 Design, 🔨 Refactor

#177 [refactor/#176] 검색창 기능 개선
  src/components/common/Search.tsx
  src/components/common/SearchModal.tsx
  src/components/common/SearchModalButton.tsx
  src/pages/mypage/medicines/index.tsx
Labels: 🔨 Refactor

#175 [feat/#164] 마이페이지 상비약 스크랩 연결
  src/components/common/MedicineCard.tsx
  src/hooks/medicine/useMedicineScrap.ts
  src/pages/mypage/index.tsx
  src/pages/mypage/medicines/index.tsx
  src/pages/supplements/[supplementId]/index.tsx
  src/pages/supplements/components/MoreSupplements.tsx
  src/pages/supplements/components/ProductBasicInfo.tsx
  src/pages/supplements/index.tsx
  src/types/medicine.ts
Labels: ✨ Feature, 📬 API

#179 [refactor/#178] 게시글 랜덤 조회 헤더 설정
  src/components/common/SupplementCard.tsx
  src/pages/community/components/PostList.tsx
  src/pages/community/index.tsx
  src/pages/community/post/components/CommentItem.tsx
  src/pages/community/post/components/ReplyItem.tsx
  src/pages/community/post/components/ReportModal.tsx
  src/pages/login/index.tsx
  src/pages/mypage/components/PharmacysCard.tsx
  src/pages/mypage/pharmacys/index.tsx
  src/pages/mypage/supplement/index.tsx
  src/pages/supplements/[supplementId]/index.tsx
  src/pages/supplements/components/ProductBasicInfo.tsx
  src/pages/supplements/index.tsx
  src/utils/cookie.ts
Labels: 📬 API, 🔨 Refactor

#181 [feat/#180] 영양제 유지보수
  src/components/common/SupplementCard.tsx
  src/pages/supplements/[supplementId]/index.tsx
Labels: ✨ Feature, 🎨 Design, 🔨 Refactor

#183 [refactor/#182] 미 로그인 접근 시 modal/redirect 통일
  src/apis/axios-instance.ts
  src/components/common/SupplementCard.tsx
  src/components/layout/Header.tsx
  src/pages/community/activities/components/MyNotificationList.tsx
  src/pages/community/components/NoticeModal.tsx
  src/pages/community/components/UserNavbar.tsx
  src/pages/community/create/index.tsx
  src/pages/login/index.tsx
  src/pages/mypage/index.tsx
  src/pages/supplements/[supplementId]/index.tsx
  src/store/useModalStore.ts
Labels: ✨ Feature, 🔨 Refactor

#185 [feat/#162] 상비약 검색 연동
  src/components/common/MedicineCard.tsx
  src/components/common/PageNavigator.tsx
  src/components/common/Search.tsx
  src/components/layout/AdditionalHeader.tsx
  src/constants/FilterList.ts
  src/constants/MedicineCategories.ts
  src/hooks/medicine/useMedicineSearch.ts
  src/pages/medicines/components/EmptySearchResults.tsx
  src/pages/medicines/components/MedicineDetail.tsx
  src/pages/medicines/components/MedicineSearchResults.tsx
  src/pages/medicines/search/index.tsx
Labels: ✨ Feature, 📬 API

#187 [feat/#184] 스크랩 모달 수정
  src/apis/axios-instance.ts
  src/components/common/SupplementCard.tsx
  src/pages/supplements/index.tsx
Labels: ✨ Feature

#190 [refactor/#186] 검색 및 필터 버튼 개선
  src/components/common/FilterButtonList.tsx
  src/pages/community/post/components/ReportModal.tsx
  src/pages/community/posts/search/index.tsx
  src/pages/supplements/index.tsx
  src/store/useModalStore.ts
Labels: ✨ Feature, 🔨 Refactor

#192 [Refactor/#189] 상비약 리스트 ui 개선
  src/components/common/MedicineCard.tsx
  src/components/layout/Header.tsx
  src/pages/medicines/components/MedicineSearchResults.tsx
Labels: 🎨 Design, 🔨 Refactor

#193 [refactor/#188] 약국찾기 UI/UX 개선
  src/pages/map/components/MapComponent.tsx
  src/pages/map/components/detailPanel/Info.tsx
Labels: 🎨 Design, 🔨 Refactor

#194 [feat#191] 신고 댓글 UI 개선
  src/components/common/Search.tsx
  src/pages/community/index.tsx
  src/pages/community/post/components/CommentItem.tsx
  src/pages/community/post/components/CommentList.tsx
  src/pages/community/post/components/ReplyItem.tsx
  src/pages/community/post/components/ReportModal.tsx
  src/pages/community/posts/search/index.tsx
Labels: ✨ Feature, 🎨 Design

#197 [refactor/#196] 홈 필터 리스트 수정
  src/components/common/FilterButtonList.tsx
  src/components/common/SearchModal.tsx
  src/constants/FilterList.ts
Labels: 🎨 Design, 🔨 Refactor

#200 [feat/#199] 더보기 영양제 이미지 이슈 해결
  src/pages/supplements/components/ProductBasicInfo.tsx
Labels: ✨ Feature, 🎨 Design
