Repository PharmQuest/FE, pull requests merged in 2025-01, with the labels that each got.

#14 [feat/#4] 헤더 구현 완료
  pharmquest/src/components/layout/Header.tsx
  pharmquest/src/pages/index.tsx
  pharmquest/src/pages/map/index.tsx
Labels: ✨ Feature, 🎨 Design

#18 [feat/#17] 약국 찾기 ui 구현
  pharmquest/src/components/layout/Header.tsx
  pharmquest/src/pages/map/index.tsx
Labels: ✨ Feature, 🎨 Design

#19 [feat/#13] 커뮤니티 페이지 와이어프레임 구현
  pharmquest/public/svgs/comment.svg
  pharmquest/public/svgs/globe.svg
  pharmquest/public/svgs/like.svg
  pharmquest/public/svgs/scrap.svg
  pharmquest/src/mocks/popularPosts.ts
  pharmquest/src/mocks/posts.ts
  pharmquest/src/pages/community/components/BestTag.tsx
  pharmquest/src/pages/community/components/NavbarItem.tsx
  pharmquest/src/pages/community/components/PopularPostItem.tsx
  pharmquest/src/pages/community/components/PopularPostList.tsx
  pharmquest/src/pages/community/components/PostItem.tsx
  pharmquest/src/pages/community/components/PostList.tsx
  pharmquest/src/pages/community/components/SubjectTag.tsx
  pharmquest/src/pages/community/components/UserNavbar.tsx
  pharmquest/src/pages/community/index.tsx
Labels: ✨ Feature, 🎨 Design

#25 [feat/#20] 마진 등 디자인 수정
  pharmquest/src/components/layout/Header.tsx
  pharmquest/src/pages/index.tsx
  pharmquest/src/pages/map/index.tsx
Labels: 🎨 Design

#37 [feat/#34] 커뮤니티 게시글 상세 및 나의활동 와이어프레임 구현
  public/svgs/arrow-right.svg
  public/svgs/corner-down-right.svg
  public/svgs/external-link.svg
  public/svgs/index.ts
  public/svgs/kebab.svg
  public/svgs/report.svg
  src/components/common/FilterButton.tsx
  src/components/layout/AdditionalHeader.tsx
  src/components/layout/Header.tsx
  src/mocks/comments.ts
  src/mocks/popularPosts.ts
  src/mocks/postItem.ts
  src/mocks/posts.ts
  src/pages/community/activities/components/ActivitiesNav.tsx
  src/pages/community/activities/components/MyCommentItem.tsx
  src/pages/community/activities/components/MyCommentList.tsx
  src/pages/community/activities/components/MyNotificationItem.tsx
  src/pages/community/activities/components/MyNotificationList.tsx
  src/pages/community/activities/index.tsx
  src/pages/community/components/BestTag.tsx
  src/pages/community/components/GrayButton.tsx
  src/pages/community/components/NavbarItem.tsx
  src/pages/community/components/PopularPostItem.tsx
  src/pages/community/components/PopularPostList.tsx
  src/pages/community/components/PostItem.tsx
  src/pages/community/components/PostList.tsx
  src/pages/community/components/SubjectTag.tsx
  src/pages/community/components/Tag.tsx
  src/pages/community/components/UserNavbar.tsx
  src/pages/community/index.tsx
  src/pages/community/mycomment/index.tsx
  src/pages/community/mypost/index.tsx
  src/pages/community/notice/index.tsx
  src/pages/community/post/[postId]/index.tsx
  src/pages/community/post/components/CommentInput.tsx
  src/pages/community/post/components/CommentItem.tsx
  src/pages/community/post/components/CommentList.tsx
  src/pages/community/post/components/ReplyItem.tsx
  src/pages/community/post/components/ViewPost.tsx
  src/pages/community/scrap/index.tsx
Labels: ✨ Feature, 🎨 Design

#42 [feat/#41] 헤더 로그아웃 추가
  public/svgs/index.ts
  public/svgs/logo.svg
  public/svgs/user.svg
  src/components/common/Search.tsx
  src/components/layout/Header.tsx
  src/pages/login/index.tsx
  src/pages/map/index.tsx
Labels: ✨ Feature, 🎨 Design

#50 [feat#49] 공용 컴포넌트 수정
  public/svgs/index.ts
  public/svgs/map-pin.svg
  public/svgs/search-bar.svg
  public/svgs/search.svg
  public/svgs/x.svg
  src/components/common/FilterButton.tsx
  src/components/common/Search.tsx
  src/components/layout/Header.tsx
  src/pages/index.tsx
Labels: ✨ Feature, 🎨 Design

#52 [feat/#51] 메인 반응형 구현
  public/svgs/footer_logo.svg
  public/svgs/index.ts
  src/components/common/FilterButton.tsx
  src/components/common/Search.tsx
  src/components/layout/Footer.tsx
  src/components/layout/Header.tsx
  src/pages/index.tsx
  src/styles/globals.css
Labels: ✨ Feature, 🎨 Design

#54 [feat/#53] 1000px미만 기준 헤더 메뉴 클릭 시 사이드바 기능 구현
  public/svgs/gt.svg
  public/svgs/index.ts
  public/svgs/menu.svg
  public/svgs/white-gt.svg
  src/components/common/Search.tsx
  src/components/layout/Footer.tsx
  src/components/layout/Header.tsx
  src/pages/index.tsx
Labels: ✨ Feature, 🎨 Design

#56 [feat/#55] 검색창 x표 사이즈 수정
  public/svgs/green-map-pin.svg
  public/svgs/index.ts
  public/svgs/small-green-map-pin.svg
  src/components/common/Search.tsx
Labels: 🎨 Design

#58 [feat/#57] 메인 화면 기준 필터버튼 클릭 시 배경 흰색으로
  src/components/common/FilterButton.tsx
Labels: 🎨 Design

#60 [feat/#59] 커뮤니티 반응형 수정
  public/svgs/find-gt.svg
  public/svgs/find-lt.svg
  public/svgs/find-search.svg
  public/svgs/index.ts
  public/svgs/menu.svg
  src/pages/index.tsx
  src/pages/map/index.tsx
Labels: ✨ Feature, 🎨 Design

#65 [feat/#20] 커뮤니티랑 푸터 수정
  src/components/layout/Footer.tsx
  src/pages/index.tsx
Labels: ✨ Feature, 🎨 Design

#68 [feat/#39] 약국찾기 화면 및 기능 구현 중
  package.json
  pnpm-lock.yaml
  public/svgs/index.ts
  public/svgs/review-star.svg
  public/svgs/rotate.svg
  src/components/layout/Footer.tsx
  src/pages/map/components/IsOpenTag.tsx
  src/pages/map/components/MapComponent.tsx
  src/pages/map/components/PharmacyDetailPanel.tsx
  src/pages/map/components/PharmacyItem.tsx
  src/pages/map/components/PharmacyList.tsx
  src/pages/map/components/RatingStars.tsx
  src/pages/map/components/SearchOnCurrentMapButton.tsx
  src/pages/map/components/SearchPanel.tsx
  src/pages/map/index.tsx
Labels: ✨ Feature, 🎨 Design, 📬 API

#75 [feat/#74] 메인화면 UI/UX 개선
  public/images/.gitkeep
  public/images/index.ts
  public/images/medicine.webp
  src/pages/index.tsx
Labels: ✨ Feature, 🎨 Design
